services:
  scraper:
    build: .
    volumes:
      - ./:/app
    environment: []
    command: ["python","-m","scrapers.geo.sweep","--headless","--order","density","--panpoints","data/panpoints/airbnb_panpoints_gdl_zap.csv"]
