checkin: '2025-09-12'
checkout: '2025-09-16'
adults: 2
cities: ['gdl','zap']
panpoints_csv: 'data/panpoints/airbnb_panpoints_gdl_zap.csv'
out_csv: 'data/out/results.csv'
coverage: 'data/coverage/coverage.jsonl'
headless: true
max_scrolls: 8
max_listings: 500
